# Generated by cucumber-sinatra. (2014-11-07 12:37:42 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = bookmark_manager2

class bookmark_manager2World
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  bookmark_manager2World.new
end
